[package]
name = "gpui_3d_gltf"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "MIT"

[features]
wgpu = ["gpui_3d/wgpu"]

[dependencies]
anyhow.workspace = true
base64.workspace = true
futures.workspace = true
indexmap.workspace = true
parking_lot.workspace = true
gpui.workspace = true
gpui_3d.workspace = true
gltf = { version = "1.4.1", default-features = false, features = ["utils", "names", "extensions", "KHR_materials_unlit", "KHR_texture_transform", "KHR_lights_punctual"] }
serde_json.workspace = true
sha2.workspace = true
image.workspace = true

[dev-dependencies]
gpui_platform = { workspace = true, features = ["font-kit", "wayland", "x11"] }
tempfile.workspace = true
url.workspace = true

[lints]
workspace = true
